version: 2.1

jobs:
  build:
    docker:
      - image: circleci/dotnetcore
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build --configuration Release
      - run:
          name: Run tests
          command: dotnet test --logger "trx;LogFileName=test-results.trx"
workflows:
  version: 2
  test:
    jobs:
      - build
